package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.common.internal.w.a;
import com.google.android.gms.common.internal.w.c;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.annotation.ParametersAreNonnullByDefault;

@ParametersAreNonnullByDefault
public final class jf extends a {
    public static final Parcelable.Creator<jf> CREATOR = new Cif();
    private final List<String> A;
    private final long B;
    private final String C;
    private final float D;
    private final int E;
    private final int F;
    private final boolean G;
    private final boolean H;
    private final String I;
    private final boolean J;
    private final String K;
    private final boolean L;
    private final int M;
    private final Bundle N;
    private final String O;
    private final xp2 P;
    private final boolean Q;
    private final Bundle R;
    private final String S;
    private final String T;
    private final String U;
    private final boolean V;
    private final List<Integer> W;
    private final String X;
    private final List<String> Y;
    private final int Z;
    private final boolean a0;

    /* renamed from: b  reason: collision with root package name */
    private final int f3211b;
    private final boolean b0;

    /* renamed from: c  reason: collision with root package name */
    private final Bundle f3212c;
    private final boolean c0;
    private final rm2 d;
    private final ArrayList<String> d0;
    private final um2 e;
    private final String e0;
    private final String f;
    private final q6 f0;
    private final ApplicationInfo g;
    private final String g0;
    private final PackageInfo h;
    private final Bundle h0;
    private final String i;
    private final String j;
    private final String k;
    private final fo l;
    private final Bundle m;
    private final int n;
    private final List<String> o;
    private final Bundle p;
    private final boolean q;
    private final int r;
    private final int s;
    private final float t;
    private final String u;
    private final long v;
    private final String w;
    private final List<String> x;
    private final String y;
    private final m1 z;

    jf(int i2, Bundle bundle, rm2 rm2, um2 um2, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, fo foVar, Bundle bundle2, int i3, List<String> list, Bundle bundle3, boolean z2, int i4, int i5, float f2, String str5, long j2, String str6, List<String> list2, String str7, m1 m1Var, List<String> list3, long j3, String str8, float f3, boolean z3, int i6, int i7, boolean z4, boolean z5, String str9, String str10, boolean z6, int i8, Bundle bundle4, String str11, xp2 xp2, boolean z7, Bundle bundle5, String str12, String str13, String str14, boolean z8, List<Integer> list4, String str15, List<String> list5, int i9, boolean z9, boolean z10, boolean z11, ArrayList<String> arrayList, String str16, q6 q6Var, String str17, Bundle bundle6) {
        this.f3211b = i2;
        this.f3212c = bundle;
        this.d = rm2;
        this.e = um2;
        this.f = str;
        this.g = applicationInfo;
        this.h = packageInfo;
        this.i = str2;
        this.j = str3;
        this.k = str4;
        this.l = foVar;
        this.m = bundle2;
        this.n = i3;
        this.o = list;
        this.A = list3 == null ? Collections.emptyList() : Collections.unmodifiableList(list3);
        this.p = bundle3;
        this.q = z2;
        this.r = i4;
        this.s = i5;
        this.t = f2;
        this.u = str5;
        this.v = j2;
        this.w = str6;
        this.x = list2 == null ? Collections.emptyList() : Collections.unmodifiableList(list2);
        this.y = str7;
        this.z = m1Var;
        this.B = j3;
        this.C = str8;
        this.D = f3;
        this.J = z3;
        this.E = i6;
        this.F = i7;
        this.G = z4;
        this.H = z5;
        this.I = str9;
        this.K = str10;
        this.L = z6;
        this.M = i8;
        this.N = bundle4;
        this.O = str11;
        this.P = xp2;
        this.Q = z7;
        this.R = bundle5;
        this.S = str12;
        this.T = str13;
        this.U = str14;
        this.V = z8;
        this.W = list4;
        this.X = str15;
        this.Y = list5;
        this.Z = i9;
        this.a0 = z9;
        this.b0 = z10;
        this.c0 = z11;
        this.d0 = arrayList;
        this.e0 = str16;
        this.f0 = q6Var;
        this.g0 = str17;
        this.h0 = bundle6;
    }

    public final void writeToParcel(Parcel parcel, int i2) {
        int a2 = c.a(parcel);
        c.a(parcel, 1, this.f3211b);
        c.a(parcel, 2, this.f3212c, false);
        c.a(parcel, 3, (Parcelable) this.d, i2, false);
        c.a(parcel, 4, (Parcelable) this.e, i2, false);
        c.a(parcel, 5, this.f, false);
        c.a(parcel, 6, (Parcelable) this.g, i2, false);
        c.a(parcel, 7, (Parcelable) this.h, i2, false);
        c.a(parcel, 8, this.i, false);
        c.a(parcel, 9, this.j, false);
        c.a(parcel, 10, this.k, false);
        c.a(parcel, 11, (Parcelable) this.l, i2, false);
        c.a(parcel, 12, this.m, false);
        c.a(parcel, 13, this.n);
        c.b(parcel, 14, this.o, false);
        c.a(parcel, 15, this.p, false);
        c.a(parcel, 16, this.q);
        c.a(parcel, 18, this.r);
        c.a(parcel, 19, this.s);
        c.a(parcel, 20, this.t);
        c.a(parcel, 21, this.u, false);
        c.a(parcel, 25, this.v);
        c.a(parcel, 26, this.w, false);
        c.b(parcel, 27, this.x, false);
        c.a(parcel, 28, this.y, false);
        c.a(parcel, 29, (Parcelable) this.z, i2, false);
        c.b(parcel, 30, this.A, false);
        c.a(parcel, 31, this.B);
        c.a(parcel, 33, this.C, false);
        c.a(parcel, 34, this.D);
        c.a(parcel, 35, this.E);
        c.a(parcel, 36, this.F);
        c.a(parcel, 37, this.G);
        c.a(parcel, 38, this.H);
        c.a(parcel, 39, this.I, false);
        c.a(parcel, 40, this.J);
        c.a(parcel, 41, this.K, false);
        c.a(parcel, 42, this.L);
        c.a(parcel, 43, this.M);
        c.a(parcel, 44, this.N, false);
        c.a(parcel, 45, this.O, false);
        c.a(parcel, 46, (Parcelable) this.P, i2, false);
        c.a(parcel, 47, this.Q);
        c.a(parcel, 48, this.R, false);
        c.a(parcel, 49, this.S, false);
        c.a(parcel, 50, this.T, false);
        c.a(parcel, 51, this.U, false);
        c.a(parcel, 52, this.V);
        c.a(parcel, 53, this.W, false);
        c.a(parcel, 54, this.X, false);
        c.b(parcel, 55, this.Y, false);
        c.a(parcel, 56, this.Z);
        c.a(parcel, 57, this.a0);
        c.a(parcel, 58, this.b0);
        c.a(parcel, 59, this.c0);
        c.b(parcel, 60, this.d0, false);
        c.a(parcel, 61, this.e0, false);
        c.a(parcel, 63, (Parcelable) this.f0, i2, false);
        c.a(parcel, 64, this.g0, false);
        c.a(parcel, 65, this.h0, false);
        c.a(parcel, a2);
    }
}
