package com.google.android.gms.internal.ads;

import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.text.TextUtils;
import com.google.android.gms.common.internal.w.a;
import com.google.android.gms.common.internal.w.c;
import java.util.Collections;
import java.util.List;
import javax.annotation.ParametersAreNonnullByDefault;

@ParametersAreNonnullByDefault
public final class lf extends a {
    public static final Parcelable.Creator<lf> CREATOR = new kf();
    private final String A;
    private final boolean B;
    private final boolean C;
    private final uh D;
    private final List<String> E;
    private final List<String> F;
    private final boolean G;
    private final nf H;
    private final boolean I;
    private String J;
    private final List<String> K;
    private final boolean L;
    private final String M;
    private final ui N;
    private final String O;
    private final boolean P;
    private final boolean Q;
    private Bundle R;
    private final boolean S;
    private final int T;
    private final boolean U;
    private final List<String> V;
    private final boolean W;
    private final String X;
    private String Y;
    private boolean Z;
    private boolean a0;

    /* renamed from: b  reason: collision with root package name */
    private final int f3536b;

    /* renamed from: c  reason: collision with root package name */
    private final String f3537c;
    private String d;
    private final List<String> e;
    private final int f;
    private final List<String> g;
    private final long h;
    private final boolean i;
    private final long j;
    private final List<String> k;
    private final long l;
    private final int m;
    private final String n;
    private final long o;
    private final String p;
    private final boolean q;
    private final String r;
    private final String s;
    private final boolean t;
    private final boolean u;
    private final boolean v;
    private final boolean w;
    private final boolean x;
    private yf y;
    private String z;

    lf(int i2, String str, String str2, List<String> list, int i3, List<String> list2, long j2, boolean z2, long j3, List<String> list3, long j4, int i4, String str3, long j5, String str4, boolean z3, String str5, String str6, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, yf yfVar, String str7, String str8, boolean z9, boolean z10, uh uhVar, List<String> list4, List<String> list5, boolean z11, nf nfVar, boolean z12, String str9, List<String> list6, boolean z13, String str10, ui uiVar, String str11, boolean z14, boolean z15, Bundle bundle, boolean z16, int i5, boolean z17, List<String> list7, boolean z18, String str12, String str13, boolean z19, boolean z20) {
        bg bgVar;
        this.f3536b = i2;
        this.f3537c = str;
        this.d = str2;
        List<String> list8 = null;
        this.e = list != null ? Collections.unmodifiableList(list) : null;
        this.f = i3;
        this.g = list2 != null ? Collections.unmodifiableList(list2) : null;
        this.h = j2;
        this.i = z2;
        this.j = j3;
        this.k = list3 != null ? Collections.unmodifiableList(list3) : null;
        this.l = j4;
        this.m = i4;
        this.n = str3;
        this.o = j5;
        this.p = str4;
        this.q = z3;
        this.r = str5;
        this.s = str6;
        this.t = z4;
        this.u = z5;
        this.v = z6;
        this.w = z7;
        this.P = z14;
        this.x = z8;
        this.y = yfVar;
        this.z = str7;
        this.A = str8;
        if (this.d == null && yfVar != null && (bgVar = (bg) yfVar.a(bg.CREATOR)) != null && !TextUtils.isEmpty(bgVar.f1943b)) {
            this.d = bgVar.f1943b;
        }
        this.B = z9;
        this.C = z10;
        this.D = uhVar;
        this.E = list4;
        this.F = list5;
        this.G = z11;
        this.H = nfVar;
        this.I = z12;
        this.J = str9;
        this.K = list6;
        this.L = z13;
        this.M = str10;
        this.N = uiVar;
        this.O = str11;
        this.Q = z15;
        this.R = bundle;
        this.S = z16;
        this.T = i5;
        this.U = z17;
        this.V = list7 != null ? Collections.unmodifiableList(list7) : list8;
        this.W = z18;
        this.X = str12;
        this.Y = str13;
        this.Z = z19;
        this.a0 = z20;
    }

    public final void writeToParcel(Parcel parcel, int i2) {
        int a2 = c.a(parcel);
        c.a(parcel, 1, this.f3536b);
        c.a(parcel, 2, this.f3537c, false);
        c.a(parcel, 3, this.d, false);
        c.b(parcel, 4, this.e, false);
        c.a(parcel, 5, this.f);
        c.b(parcel, 6, this.g, false);
        c.a(parcel, 7, this.h);
        c.a(parcel, 8, this.i);
        c.a(parcel, 9, this.j);
        c.b(parcel, 10, this.k, false);
        c.a(parcel, 11, this.l);
        c.a(parcel, 12, this.m);
        c.a(parcel, 13, this.n, false);
        c.a(parcel, 14, this.o);
        c.a(parcel, 15, this.p, false);
        c.a(parcel, 18, this.q);
        c.a(parcel, 19, this.r, false);
        c.a(parcel, 21, this.s, false);
        c.a(parcel, 22, this.t);
        c.a(parcel, 23, this.u);
        c.a(parcel, 24, this.v);
        c.a(parcel, 25, this.w);
        c.a(parcel, 26, this.x);
        c.a(parcel, 28, (Parcelable) this.y, i2, false);
        c.a(parcel, 29, this.z, false);
        c.a(parcel, 30, this.A, false);
        c.a(parcel, 31, this.B);
        c.a(parcel, 32, this.C);
        c.a(parcel, 33, (Parcelable) this.D, i2, false);
        c.b(parcel, 34, this.E, false);
        c.b(parcel, 35, this.F, false);
        c.a(parcel, 36, this.G);
        c.a(parcel, 37, (Parcelable) this.H, i2, false);
        c.a(parcel, 38, this.I);
        c.a(parcel, 39, this.J, false);
        c.b(parcel, 40, this.K, false);
        c.a(parcel, 42, this.L);
        c.a(parcel, 43, this.M, false);
        c.a(parcel, 44, (Parcelable) this.N, i2, false);
        c.a(parcel, 45, this.O, false);
        c.a(parcel, 46, this.P);
        c.a(parcel, 47, this.Q);
        c.a(parcel, 48, this.R, false);
        c.a(parcel, 49, this.S);
        c.a(parcel, 50, this.T);
        c.a(parcel, 51, this.U);
        c.b(parcel, 52, this.V, false);
        c.a(parcel, 53, this.W);
        c.a(parcel, 54, this.X, false);
        c.a(parcel, 55, this.Y, false);
        c.a(parcel, 56, this.Z);
        c.a(parcel, 57, this.a0);
        c.a(parcel, a2);
    }
}
